### ISSUE TITLE
'ClosedJaxpr' object has no attribute 'invars' on newer versions of jax

### ISSUE THREAD

**Issue by Akash-Harapanahalli** [deepmind/jax_verify#10]
I'm working on a machine with Cuda 12.1 installed, so I needed to install a newer version of JAX (at least 0.4.7 I believe) which leads to the following error when calling functions like `jax_verify.interval_bound_propagation` or `jax_verify.backward_crown_bound_propagation`:
```
Traceback (most recent call last):
  File "jax_verify/jax_verify/src/ibp.py", line 485, in interval_bound_propagation
    output_bound, _ = bound_propagation.bound_propagation(
  File "jax_verify/jax_verify/src/bound_propagation.py", line 229, in bound_propagation
    simplified_graph = synthetic_primitives.simplify_graph(
  File "jax_verify/jax_verify/src/synthetic_primitives.py", line 68, in simplify_graph
    return _simplify_graph(var_is_bound, graph, graph_simplifier)
  File "jax_verify/jax_verify/src/synthetic_primitives.py", line 88, in _simplify_graph
    return functools.reduce(
  File "jax_verify/jax_verify/src/synthetic_primitives.py", line 94, in _simplify_graph
    simplified_graph = graph_simplifier(graph, var_is_bound)
  File "jax_verify/jax_verify/src/synthetic_primitives.py", line 1061, in <lambda>
    activation_simplifier = lambda graph, _: activation_detector(graph)
  File "jax_verify/jax_verify/src/synthetic_primitives.py", line 1060, in <lambda>
    activation_detector = lambda graph: detect(activation_specs(), graph)
  File "jax_verify/jax_verify/src/synthetic_primitives.py", line 273, in detect
    eqn, eqn_idx = _next_equation(synthetic_primitive_specs, graph, eqn_idx)
  File "jax_verify/jax_verify/src/synthetic_primitives.py", line 299, in _next_equation
    ) = _matches(spec.graph, spec.capture_literals, graph, eqn_idx)
  File "jax_verify/jax_verify/src/synthetic_primitives.py", line 417, in _matches
    ) = _matches(subspec, capture_literals, subgraph, 0)
  File "jax_verify/jax_verify/src/synthetic_primitives.py", line 356, in _matches
    spec_invar_indices = {invar: j for j, invar in enumerate(spec.invars)}
AttributeError: 'ClosedJaxpr' object has no attribute 'invars'
```
After a little bit of digging, I found that in this version of JAX, `invars` and `outvars` are not immediately available to a `ClosedJaxpr`, but instead can be accessed through the `jaxpr` member of `ClosedJaxpr`. 

I fixed this specific line with an if statement, calling `spec.jaxpr.invars` instead when the `type(spec) == ClosedJaxpr`, but the same issue arose in other areas of the code. So for a quicker fix, I went into `jax/_src/core.py` and edited the `ClosedJaxpr` class adding the following properties:
```
invars = property(lambda self: self.jaxpr.invars)
outvars = property(lambda self: self.jaxpr.outvars)
```
which seemed to fix the issue everywhere. Is there a better solution to this issue?

**Comment by bunelr** [comment]
Hi, sorry that you encountered  this issue.

 The problem is that we haven't released a new version of jax_verify in a while, and as you identified, some of the internal jax API have changed in the meantime, which causes a conflict. The best solution would be for me to release an updated version of jax_verify, with our internal fixes (but this will take a bit of time because I'm at a conference, and we need to carve out some code that we are not ready to publish yet). I should be able to do that in two or three weeks.

In the meantime:
* The solution you have will work, if a bit hacky :) 
* I have checked in our codebase, and it seems like replacing [those lines](https://github.com/deepmind/jax_verify/blob/master/jax_verify/src/synthetic_primitives.py#L404-L405) with the following code should do the trick. This will ensure that we only keep track of `jaxpr`, rather than also dealing with `ClosedJaxpr`

```python
        if isinstance(spec_param, jax.core.ClosedJaxpr):
          assert isinstance(graph_param, jax.core.ClosedJaxpr)
          subspec = spec_param.jaxpr
          subgraph = graph_param.jaxpr
        else:
          assert isinstance(spec_param, jax.core.Jaxpr)
          assert isinstance(graph_param, jax.core.Jaxpr)
          subspec = spec_param
          subgraph = graph_param
```

**Comment by Akash-Harapanahalli** [comment]
Hi,

Thanks for the quick reply---it's no problem at all. I suspect I may be at the same conference :) Please don't feel rushed, I was mainly just testing out these verification tools within JAX, and I can easily just apply this patch.
